---
- name: Install base packages
  ansible.builtin.package:
    name:
      - chrony
      - vim
      - net-tools
      - mod_ssl
    state: present

- name: Set timezone
  community.general.timezone:
    name: Australia/Sydney

- name: Configure chrony service
  ansible.builtin.service:
    name: chronyd
    state: started
    enabled: true

- name: Harden SSH config - disable root login and password auth
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - { regexp: '^PermitRootLogin', line: 'PermitRootLogin no' }
    - { regexp: '^PasswordAuthentication', line: 'PasswordAuthentication no' }

- name: Restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted
